# Generated by Django 4.2.5 on 2023-09-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
                ('LAT', models.DecimalField(decimal_places=6, max_digits=9)),
                ('LON', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
