# Generated by Django 4.2.5 on 2023-09-27 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogParks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Review Date')),
                ('rating', models.IntegerField(choices=[(5, '5-Stars'), (4, '4-Stars'), (3, '3-Stars'), (2, '2-Stars'), (1, '1-Star')], default=5, verbose_name='User Rating')),
                ('review', models.TextField(blank=True, max_length=500)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dogparks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
