# Generated by Django 4.2.5 on 2023-09-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.IntegerField(choices=[(5, '5-Stars'), (4, '4-Stars'), (3, '3-Stars'), (2, '2-Stars'), (1, '1-Star')], default=5, max_length=1)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dogparks')),
            ],
        ),
    ]
