# Generated by Django 4.2.5 on 2023-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '5-Stars'), (4, '4-Stars'), (3, '3-Stars'), (2, '2-Stars'), (1, '1-Star')], default=5),
        ),
    ]
