# Generated by Django 4.2.5 on 2023-09-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Pictures',
        ),
    ]
