# Generated by Django 4.2.5 on 2023-09-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pictures_user_alter_pictures_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='description',
        ),
    ]
