# Generated by Django 4.2.5 on 2023-09-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_pictures_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.CharField(default='Dog Park!', max_length=100),
            preserve_default=False,
        ),
    ]
