# Generated by Django 4.2.5 on 2023-10-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_pictures_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogparks',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogparks',
            name='long',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
