# Generated by Django 4.2.5 on 2023-10-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_dogparks_lat_dogparks_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogparks',
            name='hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
