# Generated by Django 4.2.5 on 2023-10-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_dogparks_lat_alter_dogparks_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogparks',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='dogparks',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dogparks',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
