# Generated by Django 4.2.6 on 2023-10-16 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_alter_dogparks_options_alter_dogparks_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogparks',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='dogparks',
            name='long',
        ),
        migrations.AddField(
            model_name='dogparks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
