# Generated by Django 4.2.6 on 2023-10-16 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_remove_dogparks_lat_remove_dogparks_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogparks',
            name='user',
        ),
        migrations.AddField(
            model_name='dogparks',
            name='users',
            field=models.ManyToManyField(related_name='saved_parks', to=settings.AUTH_USER_MODEL),
        ),
    ]
